# This is a basic workflow to help you get started with Actions

name: kind on GitHub Actions

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: azure/setup-helm@v1

      - name: Install wsk CLI
        run: |
          wget https://github.com/apache/openwhisk-cli/releases/download/1.2.0/OpenWhisk_CLI-1.2.0-linux-amd64.tgz
          tar zxvf OpenWhisk_CLI-1.2.0-linux-amd64.tgz

      - uses: engineerd/setup-kind@v0.5.0
        with:
          skipClusterCreation: true

      - name: Create kind cluster
        id: create_kind_cluster
        run: |
          kind create cluster --config kind-cluster.yaml

          kubectl label node kind-worker openwhisk-role=core
          kubectl label node kind-worker2 openwhisk-role=invoker

          # determine the internalIP of a kind worker node
          WORKER_INTERNAL_IP=$(kubectl describe node kind-worker | grep InternalIP: | awk '{print $2}')

          echo "Worker internal IP: $WORKER_INTERNAL_IP"

          echo "::set-output name=worker_internal_ip::$WORKER_INTERNAL_IP"

      - name: Install OpenWhisk into kind cluster
        env:
          WORKER_INTERNAL_IP: ${{ steps.create_kind_cluster.outputs.worker_internal_ip }}
        run: |
          echo "Starting OpenWhisk install into kind cluster..."

          # Install from Helm
          helm repo add openwhisk https://openwhisk.apache.org/charts
          helm repo update
          helm install owdev openwhisk/openwhisk -n openwhisk --create-namespace

          echo "OpenWhisk install into kind cluster started. Waiting 6 minutes for all pods to be Completed or Running..."

          POD_STATUS_RUNNING="kubectl get pods --field-selector=status.phase!=Running --all-namespaces"
          POD_STATUS_COMPLETED="kubectl get pods --field-selector=status.phase!=Completed --all-namespaces"
          
          while [ "$(kubectl get pod --all-namespaces | grep owdev-install-packages | awk '{print $4}')" != "Completed" ]
          do
            echo "OpenWhisk install not complete yet. Waiting..."
            sleep 10
          done

          echo "Finished waiting for OpenWhisk install to complete."

      - name: Set up wsk CLI
        env:
          WSK_CMD: "./wsk -i"
        run: |
          $WSK_CMD property set --apihost "localhost:31001"
          $WSK_CMD property set --auth 23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP

      - name: Create sample action
        env:
          WSK_CMD: "./wsk -i"
        run: |
          $WSK_CMD action create hello "sample-action/main.js"

      - name: Invoke sample action
        env:
          WSK_CMD: "./wsk -i"
        run: |
          $WSK_CMD action invoke hello --blocking
